### ISSUE TITLE
Add support for boolean attributes.

### ISSUE THREAD

**Issue by sorodrigo** [vihanb/babel-plugin-jsx-to-dom#1]
I found a little confusing the fact that boolean attributes are directly passed as strings, this goes against the react jsx implementation and hinders the improvement in dx that this plugin brings.

**Comment by vihanb** [comment]
do you mean that `<Element attr={true} />` is doing `el.attr = "true"` atm whereas it should do `el.attr = true`?

**Comment by sorodrigo** [comment]
Yes sort of... `<Element attr={valueA === valueB} />` is doing `el.attr = "true"` and/or `el.attr = "false"` which in the last case is still `true`.

**Comment by vihanb** [comment]
Any specific attribute where this is the case? Because right now we're using setAttribute() so that way things like `aria-label` or `class` works. setAttribute internally converts the value to a string so the alternative is either a finicky transformation or alternative handling of attributes which take booleans

**Comment by sorodrigo** [comment]
I would do it for all attributes with a boolean value. Because transforming to string can have unexpected behavior.

As an example I can think of `<option selected>`

**Comment by vihanb** [comment]
@sorodrigo ok in latest version to not use `setAttribute` you can use `unsafe-` so for example `<option unsafe-selected={ isSelected } />`
